apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod 
spec:
  containers: 
  - image: nginx:1.14.0
    name: nginx-pod
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
  volumes:
  - name: data
